pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                bat '''
                    cd internship_SimberSoft_CI
                    C:\\Python39\\python.exe -m pip install -r requirements.txt
                    C:\\Python39\\python.exe -m pip install allure-pytest==2.13.2
                '''
            }
        }

        stage('Test') {
            steps {
                bat '''
                    cd internship_SimberSoft_CI
                    C:\\Python39\\python.exe -m pytest tests ^
                        --junitxml=test-results.xml ^
                        -v ^
                        --alluredir=allure-results
                '''
            }
        }
    }

    post {
        always {
            // ✅ ПРОСТОЙ ПУТЬ - ОДНА ПАПКА!
            allure([
                results: [[path: 'internship_SimberSoft_CI/allure-results']],
                reportBuildPolicy: 'ALWAYS'
            ])

            // ✅ JUnit тоже простой путь
            junit 'internship_SimberSoft_CI/test-results.xml'
        }
    }
}